### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by timweissenfels** [awdeorio/supermakefilecxx#5]
Always stuck in endless loops in make test etc.

**Comment by awdeorio** [comment]
Does this happen with unmodified files from the repo?  Did you add any files?  Remove any?  Modify any?

**Comment by timweissenfels** [comment]
Nope tried it with the example everything fine.
Maybe it cant handle the catch 2 test or something?

**Comment by awdeorio** [comment]
I'm having trouble replicating the problem.  Here's what I did:

```console
$ git clone git@github.com:awdeorio/supermakefilecxx.git
$ cd supermakefilecxx/
$ make test
```

**Comment by timweissenfels** [comment]
What are you exactly trying to reproduce?

**Comment by awdeorio** [comment]
I am trying to reproduce the bug you are reporting here.

**Comment by timweissenfels** [comment]
Yeah i know but as i pointed out...  This error only occurs when using it with catch2.
Thats why i asked u what u tryin to reproduce :)

**Comment by awdeorio** [comment]
Please provide the exact files and exact commands needed to reproduce this bug.

**Comment by timweissenfels** [comment]
command was: make unittest

code example(not allowed to post the real tests):

```
TEST_CASE("Fibonacci") {
    CHECK(Fibonacci(0) == 1);
 
    CHECK(Fibonacci(5) == 8);

    BENCHMARK("Fibonacci 20") {
        return Fibonacci(20);
    };

    BENCHMARK("Fibonacci 25") {
        return Fibonacci(25);
    };

    BENCHMARK("Fibonacci 30") {
        return Fibonacci(30);
    };

    BENCHMARK("Fibonacci 35") {
        return Fibonacci(35);
    };
}
```

**Comment by timweissenfels** [comment]
I Dont have a output dumb right now but it goes like this: test passed test passed test passed
 and so on

**Comment by awdeorio** [comment]
Thanks for the added detail.  If you could post some "dummy files" that still contain the problem, I'd be happy to take a look.

**Comment by timweissenfels** [comment]
Soory for the late response i was quite busy.

```
TEST_CASE("Database initialisation") {

database db("sample.txt");
    db.read();

    REQUIRE( db.get_vec_size() == 200);

    SECTION("INSERT") {
        entry ele1("Dummy","Data","Element");
		db.insert(ele1);
		REQUIRE( db.get_vec_size() == 201);
		entry check = db[200];
		REQUIRE(check == ele1);
    }
    SECTION("DELETE") {
		entry ele1("Dummy","Data","Element");
		db + ele1;
		REQUIRE(db.get_vec_size() == 201);
		db - ele1;
		REQUIRE(db.get_vec_size() == 200);

		db + ele1;

		REQUIRE(db.get_ele(199) == ele1);
    }
    SECTION("CHANGE") {
		entry ele1("Dummy", "Data", "Element");
		entry buffer = db.get_ele(100);
		REQUIRE(db.get_ele(100) == buffer);
		db.change(100, ele1);
		REQUIRE(db.get_ele(100) == ele1);
		REQUIRE_FALSE(db.get_ele(100) == buffer);
    }
}
```

this is a very similar test,
i hope it helps.

**Comment by awdeorio** [comment]
Hmmm, looks like I would need to know all the files and libraries to recreate the problem.  Perhaps you could upload a tarball containing a simplified version of your files.

**Comment by timweissenfels** [comment]
Soory that i cant provide that in the moment.
But thanks for your help
